### ISSUE TITLE
Increase coverage of the associations middleware

### ISSUE THREAD

**Issue by albertopq** [mozilla-sensorweb/sensorthings#158]
There are some lines that need to be covered in 

https://coveralls.io/builds/9181171/source?filename=src%2Fmiddlewares%2Fassociations.js

**Comment by russnicoletti** [comment]
It seems some lines of code without coverage may be dead code. The following lines -- https://github.com/mozilla-sensorweb/sensorthings/blob/master/src/middlewares/associations.js#L98-L112 seem unreachable due to these lines -- https://github.com/mozilla-sensorweb/sensorthings/blob/master/src/middlewares/associations.js#L80-L82.

I commented out lines 98-112 and ran the coverage tests; they all passed. 

With lines 98-112 commented out, I manually sent requests like 'GET "http://localhost:8080/v1.0/Things(5)/Locations(4)/HistoricalLocations', which appeared to function properly.

**Comment by albertopq** [comment]
Yeah, it seems that we have some dead code, but I think that the wrong lines are L80-L82. This code is verifying that the associations are real, so in the example you were testing, was Locations(4) actually associated to Things(5)? If that wasn't the case, it should return an error.

**Comment by russnicoletti** [comment]
Ok, it seems L98-L112 should be kept and L80-L82 should be removed. I will test that theory.

**Comment by russnicoletti** [comment]
I verified the theory, that L98-L112 are needed and L80-L82 are not. With L80-L82 and without L98-L112,  'GET "http://localhost:8080/v1.0/Things(5)/Locations(4)/HistoricalLocations' does not return an error when 'Things(5)' is not associated with 'Locations(4)'. Without L80-L82 and with L98-L112, 404 is returned.

**Comment by ferjm** [comment]
Fixed by #210
