### ISSUE TITLE
Website query feature dependencies ($expand, geospatial-filter)

### ISSUE THREAD

**Issue by mcav** [mozilla-sensorweb/sensorthings#212]
Right now the website pulls the following graph:

- GET /Datastreams
- for each datastream, fetch `Observations@iot.navigationLink`
- for each observation, fetch`Thing@iot.navigationLink`
- for each thing, fetch `Locations@iot.navigationLink`

(paging with `@iot.nextLink` TBD on my end soon)

There are two things that we'll want to do before opening this up to people: (1) filtering by map bounds, and (2) coalescing these HTTP requests with $expand. It looks like [you committed the implementation for $expand][1], but I'm not seeing the results on the API server yet ([example link][2]).

So I have a couple questions:

1. Assuming $expand was fully-functional, would a request like the following be correct/ideal?

    `/Datastreams?$expand=Observations/Thing/Locations`

2. I think the only critical query options for the website are as follows:

    - Filter by GPS, either with something like `location/coordinates ge 25,121` or with `geo.intersects` or with `st_within` (which all seem equivalent to me? Maybe the first one ([issue 199][3]) is enough?)
    - Hierarchical $expand functionality ([issue 185][4])

    Any idea where those fall in your timelines?

Thanks!

[1]: https://github.com/mozilla-sensorweb/sensorthings/issues/101
[2]: http://api.bewrosnes.org/v1.0/Datastreams?$expand=Things
[3]: https://github.com/mozilla-sensorweb/sensorthings/issues/199
[4]: https://github.com/mozilla-sensorweb/sensorthings/issues/185

**Comment by albertopq** [comment]
Hi Marcus! I'll try to reply to your questions:

1.- At the moment, multilevel expand is not supported [1]. Basically, you cannot expand to modelA/modelB yet. Other than that, the request looks correct to me. Regarding the fact that you don't see the results in the server, I think is because of a missing deployment. I'll look into that.

2.- We'll prioritize any of those options for gps filtering and multilevel expand for the next sprint, so it should be landing around the next 2 weeks.

Thanks!

[1] https://github.com/mozilla-sensorweb/sensorthings/commit/835896235c631b5339978c372b1e8359a824f5a0#diff-a92d831a73cadec7758d16f167a8198eR266

**Comment by ferjm** [comment]
`$expand` and basic `$filter` are already implemented. Improved geo queries are going to be implemented during sprint 7 at #227.
